project:
  type: website
  output-dir: docs
website:
  title: "M S Vamsidhar Reddy"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - More.qmd
      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    page layout: full

editor: visual

